# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageunit',
            options={'permissions': (('can_list_units', 'Ver listado de unidades de almacenamiento'), ('can_create_units', 'Crear unidad de almacenamiento'), ('can_view_unit_detail', 'Ver detalle de una unidad de almacenamiento'), ('can_view_storage_content', 'Ver detalle de una unidad de almacenamiento'), ('can_download_file', 'Descargar un archivo'), ('can_view_content_detail', 'Ver detalle de un contenido'), ('can_download_metadata', 'Descargar metadados'))},
        ),
    ]
