# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestedcontent',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='ingestedcontent',
            name='storage_unit',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='IngestedContent',
        ),
    ]
