# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunit',
            name='metadata',
            field=models.FileField(upload_to=b''),
        ),
    ]
