# Generated by Django 2.1.7 on 2019-05-21 22:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20161208_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageunit',
            options={'permissions': (('can_list_units', 'Ver listado de unidades de almacenamiento'), ('can_create_units', 'Crear unidad de almacenamiento'), ('can_view_unit_detail', 'Ver detalle de una unidad de almacenamiento'), ('can_view_storage_content', 'Ver contenido de una unidad de almacenamiento'), ('can_download_file', 'Descargar un archivo'), ('can_view_content_detail', 'Ver detalle de un contenido'), ('can_download_metadata', 'Descargar metadados'), ('can_edit_units', 'Editar unidad de almacenamiento'))},
        ),
        migrations.AddField(
            model_name='storageunit',
            name='alias',
            field=models.CharField(default='no definido', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='root_dir',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
