# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20161208_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageunit',
            options={'permissions': (('can_list_units', 'Ver listado de unidades de almacenamiento'), ('can_create_units', 'Crear unidad de almacenamiento'), ('can_view_unit_detail', 'Ver detalle de una unidad de almacenamiento'), ('can_view_storage_content', 'Ver contenido de una unidad de almacenamiento'), ('can_download_file', 'Descargar un archivo'), ('can_view_content_detail', 'Ver detalle de un contenido'), ('can_download_metadata', 'Descargar metadados'), ('can_edit_units', 'Editar unidad de almacenamiento'))},
        ),
        migrations.AddField(
            model_name='storageunit',
            name='alias',
            field=models.CharField(default='unidad', max_length=200),
        ),
    ]
