# Generated by Django 2.1.7 on 2019-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20190521_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='alias',
            field=models.CharField(default='no definido', max_length=200, unique=True),
        ),
    ]
