# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storageunitceos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunitcdcol',
            name='storage_unit',
        ),
        migrations.RemoveField(
            model_name='storageunitceos',
            name='source_storage_unit',
        ),
        migrations.RemoveField(
            model_name='storageunitceos',
            name='storage_unit',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='file_description',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='processing_level',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='root_dir',
        ),
        migrations.RemoveField(
            model_name='storageunit',
            name='storage_unit_type',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='description_file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageunit',
            name='ingest_file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StorageUnitCDCOL',
        ),
        migrations.DeleteModel(
            name='StorageUnitCEOS',
        ),
    ]
