# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20160906_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestedContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.Content')),
                ('path', models.CharField(max_length=200)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageUnit')),
            ],
            bases=('storage.content',),
        ),
    ]
