# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:47
from __future__ import unicode_literals

import algorithm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_list_algorithms', 'Listar los algoritmos'), ('can_create_algorithm', 'Crear un algoritmo'), ('can_view_algorithm_detail', 'Ver detalle de un algoritmo'), ('can_edit_algorithm', 'Editar algoritmo'), ('can_create_new_version', 'Crear una nueva versi\xf3n de un algoritmo'), ('can_view_version_detail', 'Ver detalle de la versi\xf3n de un algoritmo'), ('can_edit_version', 'Editar una versi\xf3n de un algoritmo'), ('can_publish_version', 'Publicar versi\xf3n de un algoritmo'), ('can_unpublish_version', 'Despublicar versi\xf3n de un algoritmo'), ('can_deprecate_version', 'Volver versi\xf3n de un algoritmo obsoleta'), ('can_delete_version', 'Eliminar versi\xf3n de un algoritmo (si no tiene ejecuciones)'), ('can_create_parameter', 'Crear par\xe1metro para una versi\xf3n de un algoritmo'), ('can_view_parameter_detail', 'Ver detalle de un par\xe1metro de una versi\xf3n de un algoritmo'), ('can_edit_parameter', 'Editar par\xe1metro de una versi\xf3n de un algoritmo (tener en cuenta posibles variabilidades por tipo de par\xe1metro)'), ('can_view_ratings', 'Ver listado de calificaciones de una versi\xf3n de un algoritmo')),
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parameter_type', models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DOUBLE'), ('4', 'BOOLEAN'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO CON BANDAS'), ('9', 'PERIODO DE TIEMPO'), ('12', 'ARCHIVO'), ('13', 'UNIDAD ALMACENAMIENTO SIN BANDAS')], max_length=2)),
                ('description', models.TextField()),
                ('help_text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('default_value', models.CharField(default='', max_length=200)),
                ('function_name', models.CharField(default='', max_length=200)),
                ('output_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.CharField(max_length=200)),
                ('repository_url', models.CharField(max_length=300)),
                ('source_code', models.FileField(blank=True, null=True, upload_to=algorithm.models.upload_to)),
                ('publishing_state', models.CharField(choices=[('1', 'EN DESARROLLO'), ('2', 'PUBLICADA'), ('3', 'OBSOLETA')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Algorithm')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionStorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_storage_unit', to='storage.StorageUnit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_version', to='algorithm.Version')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='source_storage_units',
            field=models.ManyToManyField(through='algorithm.VersionStorageUnit', to='storage.StorageUnit'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Topic'),
        ),
    ]
