# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parameter_type', models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DECIMAL'), ('4', 'BOOLEAN'), ('5', 'FECHA'), ('6', 'FECHA Y HORA'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO'), ('9', 'PERIODO DE TIEMPO'), ('10', 'LISTA DE SELECCI\xd3N \xdaNICA'), ('11', 'LISTA DE SELECCI\xd3N M\xdaLTIPLE'), ('12', 'FILE')], max_length=2)),
                ('description', models.TextField()),
                ('help_text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('default_value', models.CharField(default='', max_length=200)),
                ('function_name', models.CharField(default='', max_length=200)),
                ('output_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.CharField(max_length=200)),
                ('source_code', models.CharField(max_length=200)),
                ('publishing_state', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Algorithm')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionStorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_storage_unit', to='storage.StorageUnit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_version', to='algorithm.Version')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='source_storage_units',
            field=models.ManyToManyField(through='algorithm.VersionStorageUnit', to='storage.StorageUnit'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Topic'),
        ),
    ]
