# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='publishing_state',
            field=models.CharField(choices=[('1', 'EN DESARROLLO'), ('2', 'PUBLICADA'), ('3', 'OBSOLETA')], max_length=2),
        ),
    ]
