# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
