# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='source_code',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
