# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_algorithm_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='display_name',
        ),
    ]
