# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 02:44
from __future__ import unicode_literals

import algorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20161202_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='source_code',
            field=models.FileField(blank=True, null=True, upload_to=algorithm.models.upload_to),
        ),
    ]
