# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 22:39
from __future__ import unicode_literals

import algorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_remove_algorithm_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='source_code',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=algorithm.models.upload_to),
        ),
    ]
