# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20161130_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DOUBLE'), ('4', 'BOOLEAN'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO CON BANDAS'), ('9', 'PERIODO DE TIEMPO'), ('12', 'ARCHIVO'), ('13', 'UNIDAD ALMACENAMIENTO SIN BANDAS')], max_length=2),
        ),
    ]
