# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='output_storage_unit',
        ),
    ]
