# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_auto_20161213_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
