# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_remove_algorithm_output_storage_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parameter_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('help_text', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('default_value', models.CharField(default='', max_length=200)),
                ('function_name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version')),
            ],
        ),
    ]
