# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_auto_20170108_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='generate_mosaic',
            field=models.BooleanField(default=False),
        ),
    ]
