# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[(1, 'STRING'), (2, 'INTEGER'), (3, 'DECIMAL'), (4, 'BOOLEAN'), (5, 'FECHA'), (6, 'FECHA Y HORA'), (7, 'AREA'), (8, 'UNIDAD ALMACENAMIENTO'), (9, 'PERIODO DE TIEMPO'), (10, 'LISTA DE SELECCI\xd3N \xdaNICA'), (11, 'LISTA DE SELECCI\xd3N M\xdaLTIPLE'), (12, 'FILE')], max_length=200),
        ),
    ]
