# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20160906_2358'),
        ('algorithm', '0006_auto_20160927_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionStorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_storage_unit', to='storage.StorageUnit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_version', to='algorithm.Version')),
            ],
        ),
        migrations.RemoveField(
            model_name='algorithmstorageunit',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='algorithmstorageunit',
            name='storage_unit',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='source_storage_units',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DECIMAL'), ('4', 'BOOLEAN'), ('5', 'FECHA'), ('6', 'FECHA Y HORA'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO'), ('9', 'PERIODO DE TIEMPO'), ('10', 'LISTA DE SELECCI\xd3N \xdaNICA'), ('11', 'LISTA DE SELECCI\xd3N M\xdaLTIPLE'), ('12', 'FILE')], max_length=2),
        ),
        migrations.DeleteModel(
            name='AlgorithmStorageUnit',
        ),
        migrations.AddField(
            model_name='version',
            name='source_storage_units',
            field=models.ManyToManyField(through='algorithm.VersionStorageUnit', to='storage.StorageUnit'),
        ),
    ]
