# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_algorithm_generate_mosaic'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='multitemporal',
            field=models.BooleanField(default=False),
        ),
    ]
