# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_auto_20160927_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='output_included',
            field=models.BooleanField(default=False),
        ),
    ]
