# Generated by Django 2.1.7 on 2019-05-31 21:00

import algorithm.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_algorithm_multitemporal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': (('can_list_versions', 'Ver listado de Versiones'), ('can_send_version_to_review', 'Enviar a revisión una versión del algoritmo'), ('can_start_version_review', 'Iniciar Revisión Versión'))},
        ),
        migrations.RemoveField(
            model_name='version',
            name='created_by',
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='No definido', max_length=200),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DOUBLE'), ('4', 'BOOLEAN'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO CON BANDAS'), ('9', 'PERIODO DE TIEMPO'), ('12', 'ARCHIVO'), ('13', 'UNIDAD ALMACENAMIENTO SIN BANDAS'), ('14', 'MULTI UNIDAD DE ALMACENAMIENTO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='version',
            name='publishing_state',
            field=models.CharField(choices=[('1', 'EN DESARROLLO'), ('4', 'PENDIENTE DE REVISION'), ('5', 'EN REVISION'), ('2', 'PUBLICADA'), ('3', 'OBSOLETA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='version',
            name='source_code',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/web_storage'), upload_to=algorithm.models.upload_to),
        ),
        migrations.AlterField(
            model_name='versionstorageunit',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageUnit'),
        ),
        migrations.AlterField(
            model_name='versionstorageunit',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version'),
        ),
    ]
