# Generated by Django 2.1.7 on 2019-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_auto_20190521_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('1', 'STRING'), ('2', 'INTEGER'), ('3', 'DOUBLE'), ('4', 'BOOLEAN'), ('7', 'AREA'), ('8', 'UNIDAD ALMACENAMIENTO CON BANDAS'), ('9', 'PERIODO DE TIEMPO'), ('12', 'ARCHIVO'), ('13', 'UNIDAD ALMACENAMIENTO SIN BANDAS'), ('14', 'MULTI UNIDAD DE ALMACENAMIENTO')], max_length=2),
        ),
    ]
