# Generated by Django 2.1.7 on 2019-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0009_auto_20190529_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='No definido', max_length=200),
        ),
    ]
