# Generated by Django 2.1.7 on 2019-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yaml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='template/yaml/')),
                ('ttype', models.CharField(choices=[('1', 'DESCRIPCIÓN'), ('2', 'INGESTA')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('can_list_yaml_templates', 'Ver listado de plantillas de archivos YML'), ('can_download_yaml_template', 'Descargar plantilla de archivo YML')),
            },
        ),
    ]
