# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'PROGRAMADA'), ('2', 'EN EJECUCI\xd3N'), ('3', 'CON FALLO'), ('4', 'COMPLETADA')], max_length=2)),
                ('comments', models.TextField()),
                ('error_messages', models.TextField()),
                ('logs', models.TextField()),
                ('start_execution_date', models.DateField(blank=True, null=True)),
                ('end_execution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_author', to=settings.AUTH_USER_MODEL)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_storage_unit', to='storage.StorageUnit')),
            ],
            options={
                'permissions': (('can_list_storage_tasks', 'Ver listado de tareas de ingesta'), ('can_create_storage_task', 'Programar una nueva tarea de ingesta'), ('can_view_storage_task_detail', 'Ver detalle de una tarea de ingesta')),
            },
        ),
    ]
