# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_content_ingestedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'PROGRAMADA'), ('2', 'EN EJECUCI\xd3N'), ('3', 'CON FALLO'), ('4', 'COMPLETADA')], max_length=2)),
                ('errors', models.TextField()),
                ('start_execution_date', models.DateField()),
                ('end_execution_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_author', to=settings.AUTH_USER_MODEL)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_storage_unit', to='storage.StorageUnit')),
            ],
        ),
    ]
