# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesttask',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
