# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingesttask',
            options={'permissions': (('can_list_storage_task', 'Ver listado de tareas de ingesta'), ('can_create_storage_task', 'Programar una nueva tarea de ingesta'), ('can_view_storage_task_detail', 'Ver detalle de una tarea de ingesta'))},
        ),
    ]
