# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-02 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingesttask',
            name='end_execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingesttask',
            name='start_execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
