# Generated by Django 2.1.7 on 2019-05-31 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20180201_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingesttask',
            options={'permissions': (('can_list_storage_tasks', 'Ver listado de tareas de ingesta'), ('can_create_storage_task', 'Programar una nueva tarea de ingesta'))},
        ),
        migrations.AlterField(
            model_name='ingesttask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingesttask',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageUnit'),
        ),
    ]
