# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20161108_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingesttask',
            old_name='description',
            new_name='comments',
        ),
    ]
