# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_auto_20161109_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesttask',
            name='logs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
