# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import ingest_template.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=ingest_template.models.get_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('can_list_ingest_templates', 'Ver listado de scritps de generaci\xf3n de metadatos'), ('can_download_metadata_script', 'Descargar scripts de generaci\xf3n de metadatos (.py)')),
            },
        ),
    ]
