# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingesttemplate',
            options={'permissions': (('can_list_ingest_templates', 'Ver listado de scritps de generaci\xf3n de metadatos'), ('can_download_metadata_script', 'Descargar scripts de generaci\xf3n de metadatos (.py)'))},
        ),
    ]
