# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import template.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YamlTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=template.models.get_upload_to)),
                ('type', models.CharField(choices=[('1', 'DESCRIPCI\xd3N'), ('2', 'INGESTA')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
