# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamltemplate',
            name='type',
            field=models.CharField(choices=[('1', 'DESCRIPCI\xd3N'), ('2', 'INGESTA')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
