# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamltemplate',
            options={'permissions': (('can_list_yaml_templates', 'Ver listado de plantillas de archivos YML'), ('can_download_yaml_template', 'Descargar plantilla de archivo YML'))},
        ),
    ]
