# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import template.models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_yamltemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamltemplate',
            name='file',
            field=models.FileField(upload_to=template.models.get_upload_to),
        ),
    ]
