# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_data_admin',
            field=models.BooleanField(default=False),
        ),
    ]
