# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_is_analyst'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
