# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
