# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20161208_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_view_quick_guide_developer', 'Puede ver guia r\xe1pida de desarrolladores'), ('can_view_quick_guide_analyst', 'Puede ver guia r\xe1pida de analista'))},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credits_approved',
            field=models.IntegerField(default=8),
        ),
    ]
