# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(default='Ninguna', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='Ninguno', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usage',
            field=models.TextField(default='No definido'),
            preserve_default=False,
        ),
    ]
