# Generated by Django 2.1.7 on 2019-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190521_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits_approved',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
