# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20161102_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 12, 17, 43, 25, 64726, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 12, 17, 43, 32, 698466, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
