# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20161112_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('1', 'POR APROBACI\xd3N'), ('2', 'APROBADO'), ('3', 'RECHAZADO')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
