version: '3'
services:
  # WEB SERVICES
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=ideam_1
      - POSTGRES_USER=portal_web
      - POSTGRES_PASSWORD=CDCol_web_2016

  web:
    build: ../
    restart: on-failure
    entrypoint: ./entrypoint.sh
    env_file:
      - ../environment
    ports:
      - 8001:8000
    volumes:
      - ../:/usr/src/app
      #  Storages
      - source-storage:/source_storage
      - dc-storage:/dc_storage
      - web-storage:/web_storage
      # Static files serving with nginx
      # - static:/usr/src/app/static
    depends_on:
      - db
    # to run django in development mode
    tty: true

  # uncomment for profuction
  # nginx:
  #   image: nginx:alpine
  #   # restart: on-failure
  #   ports:
  #   - "8002:80"
  #   volumes:
  #   - static:/usr/share/nginx/html/static
  #   - ./nginx/conf.d:/etc/nginx/conf.d
  #   - web-storage:/web_storage
  #   depends_on:
  #     - web

volumes:
  static:
  source-storage:
  dc-storage:
  web-storage: