# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('1', 'ENCOLADA'), ('2', 'EN EJECUCI\xd3N'), ('3', 'CON FALLO'), ('4', 'COMPLETADA'), ('5', 'CANCELADA')], max_length=2)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trace_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_author', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Algorithm')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.Execution')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version')),
            ],
        ),
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('latitude_start', models.CharField(max_length=200)),
                ('latitude_end', models.CharField(max_length=200)),
                ('longitude_start', models.CharField(max_length=200)),
                ('longitude_end', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='BooleanType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.BooleanField(default=False)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='IntegerType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.IntegerField()),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceListType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='StorageUnitType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='StringType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='TimePeriodType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.AddField(
            model_name='executionparameter',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.Execution'),
        ),
        migrations.AddField(
            model_name='executionparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.Parameter'),
        ),
    ]
