# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='finished_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='trace_error',
            field=models.TextField(blank=True),
        ),
    ]
