# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
