# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'permissions': (('can_list_executions', 'Ver listado de ejecuciones'), ('can_view_execution_detail', 'Ver detalle de una ejecuci\xf3n'), ('can_download_execution_results', 'Descargar los resultados de la ejecuci\xf3n'), ('can_rate_execution', 'Calificar el resultado de una ejecuci\xf3n'), ('can_view_blank_execution', 'Ver listado de algoritmos para ejecutar'), ('can_create_new_execution', 'Registrar la ejecuci\xf3n de un algoritmo'), ('can_view_new_execution', 'Ver detalle y par\xe1metros de un algoritmo para ejecutar'))},
        ),
    ]
