# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import execution.models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20161205_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('file', models.FileField(upload_to=execution.models.get_upload_to)),
            ],
            bases=('execution.executionparameter',),
        ),
    ]
