# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20161005_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='trace_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
