# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20161122_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('value', models.FloatField()),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.CreateModel(
            name='StorageUnitBandType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('storage_unit_name', models.CharField(max_length=200)),
                ('bands', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.RenameModel(
            old_name='StorageUnitType',
            new_name='StorageUnitNoBandType',
        ),
        migrations.RenameField(
            model_name='storageunitnobandtype',
            old_name='value',
            new_name='storage_unit_name',
        ),
    ]
