# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('1', 'PENDIENTE'), ('2', 'RECIBIDO'), ('3', 'INICIADO'), ('4', 'EXITOSO'), ('5', 'CON FALLO'), ('6', 'ANULADO'), ('7', 'REINTENTO')], max_length=2)),
                ('state_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.Execution')),
            ],
        ),
    ]
