# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_auto_20160927_2125'),
        ('execution', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algorithm.Algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algorithm.Version'),
            preserve_default=False,
        ),
    ]
