# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_auto_20161213_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='results_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='results_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
