# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-02 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import execution.models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_auto_20170110_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvertionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('state', models.CharField(choices=[('1', 'PROGRAMADA'), ('2', 'EN EJECUCI\xd3N'), ('3', 'CON FALLO'), ('4', 'COMPLETADA')], max_length=2)),
                ('error_messages', models.TextField()),
                ('logs', models.TextField()),
                ('start_execution_date', models.DateTimeField(blank=True, null=True)),
                ('end_execution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='execution.Execution')),
            ],
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file',
            field=models.FileField(upload_to=execution.models.get_upload_to, validators=[execution.models.validate_file_extension]),
        ),
        migrations.AlterUniqueTogether(
            name='fileconvertiontask',
            unique_together=set([('execution', 'filename')]),
        ),
    ]
