# Generated by Django 2.1.7 on 2019-05-31 18:57

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import execution.models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_auto_20170110_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvertionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('state', models.CharField(choices=[('1', 'PROGRAMADA'), ('2', 'EN EJECUCIÓN'), ('3', 'CON FALLO'), ('4', 'COMPLETADA')], max_length=2)),
                ('error_messages', models.TextField()),
                ('logs', models.TextField()),
                ('start_execution_date', models.DateTimeField(blank=True, null=True)),
                ('end_execution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiStorageUnitType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('storage_unit_name', models.CharField(max_length=500)),
                ('bands', models.CharField(max_length=500)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-pk'], 'permissions': (('can_list_executions', 'Ver listado de ejecuciones'), ('can_view_execution_detail', 'Ver detalle de una ejecución'), ('can_download_execution_results', 'Descargar los resultados de la ejecución'), ('can_rate_execution', 'Calificar el resultado de una ejecución'), ('can_view_blank_execution', 'Ver listado de algoritmos para ejecutar'), ('can_create_new_execution', 'Registrar la ejecución de un algoritmo'), ('can_view_new_execution', 'Ver detalle y parámetros de un algoritmo para ejecutar'))},
        ),
        migrations.RemoveField(
            model_name='review',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='review',
            name='version',
        ),
        migrations.AddField(
            model_name='execution',
            name='credits_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='dag_id',
            field=models.CharField(default='no_definido', max_length=1000),
        ),
        migrations.AddField(
            model_name='execution',
            name='generate_mosaic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trace_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='execution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/web_storage'), upload_to=execution.models.file_upload_to, validators=[execution.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileconvertiontask',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='execution.Execution'),
        ),
        migrations.AlterUniqueTogether(
            name='fileconvertiontask',
            unique_together={('execution', 'filename')},
        ),
    ]
