# Generated by Django 2.1.7 on 2019-05-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_auto_20190521_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStorageUnitType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('storage_unit_name', models.CharField(max_length=200)),
                ('bands', models.CharField(max_length=200)),
            ],
            bases=('execution.executionparameter',),
        ),
    ]
