# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_auto_20180201_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='generate_mosaic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
