# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_auto_20180426_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='credits_aproved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trace_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
