# Generated by Django 2.1.7 on 2019-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_multistorageunittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistorageunittype',
            name='bands',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='multistorageunittype',
            name='storage_unit_name',
            field=models.CharField(max_length=500),
        ),
    ]
