# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-28 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_auto_20180528_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='credits_aproved',
            new_name='credits_consumed',
        ),
    ]
