# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_auto_20180528_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='credits_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
