# Generated by Django 2.1.7 on 2019-05-31 21:02

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import execution.models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_auto_20180607_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStorageUnitType',
            fields=[
                ('executionparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='execution.ExecutionParameter')),
                ('storage_unit_name', models.CharField(max_length=500)),
                ('bands', models.CharField(max_length=500)),
            ],
            bases=('execution.executionparameter',),
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-pk'], 'permissions': (('can_list_executions', 'Ver listado de ejecuciones'), ('can_view_execution_detail', 'Ver detalle de una ejecución'), ('can_download_execution_results', 'Descargar los resultados de la ejecución'), ('can_rate_execution', 'Calificar el resultado de una ejecución'), ('can_view_blank_execution', 'Ver listado de algoritmos para ejecutar'), ('can_create_new_execution', 'Registrar la ejecución de un algoritmo'), ('can_view_new_execution', 'Ver detalle y parámetros de un algoritmo para ejecutar'))},
        ),
        migrations.RemoveField(
            model_name='review',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='review',
            name='version',
        ),
        migrations.AddField(
            model_name='execution',
            name='dag_id',
            field=models.CharField(default='no_definido', max_length=1000),
        ),
        migrations.AlterField(
            model_name='execution',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/web_storage'), upload_to=execution.models.file_upload_to, validators=[execution.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
